version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: start docker container
          command: docker-compose up -d
      - run:
          name: composer install
          command: docker-compose exec app composer install --prefer-dist
      - run:
          name: npm install
          command: docker-compose exec app npm install
      - run:
          name: npm run
          command: docker-compose exec app npm run dev
      - run:
          name: change permission
          command: docker-compose exec app chmod -R 777 storage vendor
      - run:
          name: run PHPUnitTest
          command: docker-compose exec app vendor/bin/phpunit
